branches:
  only:
    - master
language: node_js
node_js:
  - "4.3"
env:
  - MONGODB_VERSION=2.6.11
  - MONGODB_VERSION=3.0.8
cache:
  directories:
    - $HOME/.mongodb/versions/downloads
after_success: ./node_modules/.bin/codecov
